my_file = open('file_2.txt', 'r')
content = my_file.read()
print(f'Input file: \n {content}')
my_file = open('file_2.txt', 'r')
content = my_file.readlines()
print(f'Number of lines - {len(content)}')
my_file = open('file_2.txt', 'r')
content = my_file.readlines()
for i in range(len(content)):
    print(f'Symbols {i + 1} - line {len(content[i])}')
my_file = open('file_2.txt', 'r')
content = my_file.read()
content = content.split()
print(f'Total amount - {len(content)}')
my_file.close()